import {
  Archive,
  CodeXml,
  Combine,
  Crop,
  Droplet,
  EyeOff,
  FileImage,
  FileInput,
  FileOutput,
  FileText,
  FileType,
  GitCompareArrows,
  Images,
  Layers3,
  ListOrdered,
  LockKeyhole,
  LockOpen,
  Minimize2,
  PencilRuler,
  PenTool,
  Presentation,
  RotateCw,
  Scissors,
  Sheet,
  Trash2,
  Type,
  Wrench,
} from 'lucide-react';

export const toolGroups = ['Organize', 'Mark up', 'Secure', 'Convert'];

export const tools = [
  {
    id: 'merge',
    icon: Combine,
    group: 'Organize',
    title: 'Merge PDFs',
    description: 'Combine multiple PDF files into a single document',
  },
  {
    id: 'split',
    icon: Scissors,
    group: 'Organize',
    title: 'Split PDF',
    description: 'Split a PDF into multiple documents',
  },
  {
    id: 'extract',
    icon: FileOutput,
    group: 'Organize',
    title: 'Extract Pages',
    description: 'Extract specific pages from a PDF',
  },
  {
    id: 'remove',
    icon: Trash2,
    group: 'Organize',
    title: 'Remove Pages',
    description: 'Remove specific pages from a PDF',
  },
  {
    id: 'rotate',
    icon: RotateCw,
    group: 'Organize',
    title: 'Rotate PDF',
    description: 'Rotate all pages or adjust pages individually',
  },
  {
    id: 'organize',
    icon: Layers3,
    group: 'Organize',
    title: 'Organize PDF',
    description: 'Reorder, rotate, duplicate, and delete pages',
  },
  {
    id: 'crop',
    icon: Crop,
    group: 'Organize',
    title: 'Crop PDF',
    description: 'Apply shared or independent visual crop boxes',
  },
  {
    id: 'page-numbers',
    icon: ListOrdered,
    group: 'Mark up',
    title: 'Add Page Numbers',
    description: 'Number ranges with templates, fonts, and positions',
  },
  {
    id: 'protect',
    icon: LockKeyhole,
    group: 'Secure',
    title: 'Protect PDF',
    description: 'Encrypt with passwords and explicit permissions',
  },
  {
    id: 'unlock',
    icon: LockOpen,
    group: 'Secure',
    title: 'Unlock PDF',
    description: 'Remove encryption with a known password',
  },
  {
    id: 'pdf-to-jpg',
    icon: Images,
    group: 'Convert',
    title: 'PDF to JPG',
    description: 'Render page ranges with resolution and quality controls',
  },
  {
    id: 'jpg-to-pdf',
    icon: FileImage,
    group: 'Convert',
    title: 'JPG to PDF',
    description: 'Order images with page size, orientation, and margins',
  },
  {
    id: 'watermark',
    icon: Droplet,
    group: 'Mark up',
    title: 'Watermark PDF',
    description: 'Style text or image watermarks on selected pages',
  },
  {
    id: 'edit',
    icon: PencilRuler,
    group: 'Mark up',
    title: 'Edit PDF',
    description: 'Add text, images, shapes, highlights, and notes',
  },
  {
    id: 'add-text',
    icon: Type,
    group: 'Mark up',
    title: 'Add/Edit Text',
    description: 'Add or edit custom text at a specific position',
  },
  {
    id: 'signature',
    icon: PenTool,
    group: 'Mark up',
    title: 'Add Signature',
    description: 'Add a signature image to your PDF',
  },
  {
    id: 'redact',
    icon: EyeOff,
    group: 'Mark up',
    title: 'Redact PDF',
    description: 'Permanently remove regions in a sanitized output',
  },
  {
    id: 'word-to-pdf',
    icon: FileInput,
    group: 'Convert',
    title: 'Word to PDF',
    description: 'Convert DOCX and DOC files with isolated LibreOffice',
  },
  {
    id: 'powerpoint-to-pdf',
    icon: Presentation,
    group: 'Convert',
    title: 'PowerPoint to PDF',
    description: 'Convert PPTX and PPT slides with isolated LibreOffice',
  },
  {
    id: 'excel-to-pdf',
    icon: Sheet,
    group: 'Convert',
    title: 'Excel to PDF',
    description: 'Convert XLSX and XLS with print-area controls',
  },
  {
    id: 'html-to-pdf',
    icon: CodeXml,
    group: 'Convert',
    title: 'HTML to PDF',
    description: 'Render self-contained HTML with isolated Chromium',
  },
  {
    id: 'pdf-to-markdown',
    aliases: ['/convert-markdown'],
    icon: FileText,
    group: 'Convert',
    title: 'PDF to Markdown',
    description: 'Recover structure, tables, images, and reading order',
  },
  {
    id: 'compress',
    icon: Minimize2,
    group: 'Organize',
    title: 'Compress PDF',
    description: 'Choose lossless, balanced, or extreme compression',
  },
  {
    id: 'repair',
    icon: Wrench,
    group: 'Organize',
    title: 'Repair PDF',
    description: 'Recover damaged structure with explicit warnings',
  },
  {
    id: 'pdf-to-pdfa',
    icon: Archive,
    group: 'Convert',
    title: 'PDF to PDF/A',
    description: 'Create veraPDF-validated archival profiles',
  },
  {
    id: 'compare',
    icon: GitCompareArrows,
    group: 'Organize',
    title: 'Compare PDFs',
    description: 'Inspect text, layout, and rendered-page differences',
  },
  {
    id: 'pdf-to-word',
    aliases: ['/convert-docx'],
    icon: FileType,
    group: 'Convert',
    title: 'PDF to Word',
    description: 'Recover editable structure or preserve pages visually',
  },
  {
    id: 'pdf-to-powerpoint',
    icon: Presentation,
    group: 'Convert',
    title: 'PDF to PowerPoint',
    description: 'Create editable elements or visual page slides',
  },
  {
    id: 'pdf-to-excel',
    icon: Sheet,
    group: 'Convert',
    title: 'PDF to Excel',
    description: 'Detect tables into page or table worksheets',
  },
].map((tool) => ({
  ...tool,
  path: `/${tool.id}`,
}));

export const findToolByPath = (pathname) => tools.find(
  ({ path, aliases = [] }) => path === pathname || aliases.includes(pathname),
);
